name: "My Composite Action"

description: "Simple Composite Action Practice"

inputs:
  username:
    description: "User Name"
    required: true

runs:
  using: "composite"

  steps:
    - name: Print Username
      shell: bash
      run: echo "Hello ${{ inputs.username }}"

    - name: Show Branch
      shell: bash
      run: echo "Branch = ${{ github.ref_name }}"