name: "Hello Action"

description: "My first composite action"

runs:
  using: "composite"

  steps:
    - name: Print Hello
      shell: bash
      run: echo "Hello Reddy1"

    - name: Print Message
      shell: bash
      run: echo "This is my first composite action"