name: Contains Practice

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Branch Name
        run: echo "Current branch is ${{ github.ref_name }}"

      - name: Feature Branch Found
        if: contains(github.ref_name, 'feature')

        run: echo "Condition TRUE → Branch contains 'feature'"

      - name: Feature Branch Not Found
        if: ${{ !contains(github.ref_name, 'feature') }}

        run: echo "Condition FALSE → Branch does not contain 'feature'"