name: Commit Message Check

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Commit Message
        run: echo "Commit message is '${{ github.event.head_commit.message }}'"

      - name: Deploy Message Found
        if: contains(github.event.head_commit.message, 'deploy')

        run: echo "Condition TRUE → deploy word found"

      - name: Deploy Message Not Found
        if: ${{ !contains(github.event.head_commit.message, 'deploy') }}

        run: echo "Condition FALSE → deploy word not found"