name: Expressions Practice

on:
  workflow_dispatch:

jobs:

  demo:

    runs-on: ubuntu-latest

    steps:

      - name: Repository Name
        run: echo "${{ github.repository }}"

      - name: Branch Name
        run: echo "${{ github.ref_name }}"

      - name: Triggered By
        run: echo "${{ github.actor }}"

      - name: Event Name
        run: echo "${{ github.event_name }}"