name: Composite Action Demo1

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Composite Action
        uses: ./.github/actions/hello-action